=== zxmjjf/importanceCode/src/com/book2/B3_XML/MyDTD_1.dtd
<!ELEMENT jjf (baseInformation,hobby,ability)>

<!ELEMENT baseInformation (name,birth,height)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birth (years,month,day)>
<!ELEMENT years (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT height (#PCDATA)>

<!ELEMENT hobby (first,second,third,others)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT second (#PCDATA)>
<!ELEMENT third (#PCDATA)>
<!ELEMENT others (#PCDATA)>

<!ELEMENT ability (java,HTMLCSS,MySql)>
<!ATTLIST information ability CDATA "能力">
<!ELEMENT java (#PCDATA) >
<!ELEMENT HTMLCSS (#PCDATA)>
<!ELEMENT MySql (#PCDATA)>

<!-- ATTLIST jjf:baseInformation xmlns:jjf CDATA "http://java.mynamespace.com.test1.html" -->

=== zxmjjf/importanceCode/out/production/importanceCode/com/book2/B3_XML/MyXML_3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jjf SYSTEM "E:\newIDEA\importanceCode\src\com\book2\B3_XML\MyDTD_1.dtd">
<jjf>
    <baseInformation>
        <name>姜剑锋</name>
        <birth>
            <years>1997</years>
            <month>7</month>
            <day>16</day>
        </birth>
        <height>163</height>
    </baseInformation>
    <hobby>
        <first>swimming</first>
        <second>running</second>
        <third>reading</third>
        <others>Playing basketball, watching movies, climbing mountains and so on</others>
    </hobby>
    <ability>
        <java>master</java>
        <HTMLCSS>into a subject</HTMLCSS>
        <MySql>into a subject</MySql>
    </ability>
</jjf>
